name: PHP Lint

on:
  push:
    paths:
      - '**/*.php'
      - '.github/workflows/php-lint.yml'
  pull_request:
    paths:
      - '**/*.php'
      - '.github/workflows/php-lint.yml'

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run php -l on all files
        run: |
          find . -name '*.php' -print0 | xargs -0 -n 1 php -l
